### ISSUE TITLE
Titoli in colori diversi

### ISSUE THREAD

**Issue by libremente** [Open-Education-Polito/oep-python-interactive-book#14]
## Expected behaviour
I titoli dovrebbero tutti avere lo stesso colore
## Actual behaviour
![schermata da 2018-02-01 12-56-02](https://user-images.githubusercontent.com/25111463/35677291-4cf77c22-074f-11e8-93a6-93c5a6804423.png)
Alcuni titoli sono in blu, altri in rosso
## Step to reproduce the behaviour
Già nel toc dell'index si vedono i titoli in blu
## Assign to
- [x] @Styddy 
- [ ] @simonecasile 
- [ ] @ceolonimatteo 
- [ ] @CristianPonte

**Comment by Styddy** [comment]
Alcuni titoli sono in grassetto, cambio anche quelli?
@libremente
