### ISSUE TITLE
Aggiungere activecode

### ISSUE THREAD

**Issue by ceolonimatteo** [Open-Education-Polito/oep-python-interactive-book#18]
## Expected behaviour
Aggiungere un blocco activecode alla fine del primo e del terzo capitolo in modo tale che ci si può eserictare.
## Step to reproduce the behaviour
Fine capitolo 1 e fne capitolo 3.
## Assign to 
@Styddy 
@CristianPonte 
@simonecasile

**Comment by libremente** [comment]
Ok @ceolonimatteo puoi farlo tu, grazie!

**Comment by ceolonimatteo** [comment]
va bene

**Comment by libremente** [comment]
Fixed by @simonecasile 1106414c1f4cf0a6d00c8fbc707b6ef0c33100c1  closing this, thanks
